[versions]
kotlinx-serialization = "1.7.3"
junit-version = "5.10.0"

[libraries]
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit-version" }